include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_single_quotes
    - avoid_print
    - require_trailing_commas
    - prefer_const_constructors
    - prefer_const_declarations
    - unnecessary_this
